name: Deploy to Cloud Run

env:
  SERVICE_NAME: githubflask
  PROJECT_ID: flaskdockerdeploy
  DOCKER_IMAGE_URL: europe-west4-docker.pkg.dev/flaskdockerdeploy/flaskdocker/flaskimg
  IMAGE_TAG: europe-west4-docker.pkg.dev/flaskdockerdeploy/flaskdocker/flaskimg:${{ github.sha }} # Unique tag using commit SHA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.IMAGE_TAG }} -f Dockerfile .
          docker push ${{ env.IMAGE_TAG }}

      - name: Deploy to Cloud Run
        run: |
          echo SERVICE_NAME $SERVICE_NAME
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.IMAGE_TAG }} \
            --platform managed \
            --region us-east1 \
            --allow-unauthenticated
